version: '3.8'

services:
  postgresdb:
    extends:
      file: ../pweb-b/docker-compose.yaml
      service: postgresdb

  bweb:
    extends:
      file: ../pweb-b/docker-compose.yaml
      service: backend
    depends_on:
      - postgresdb

  fweb:
    extends:
      file: ../pweb-f/docker-compose.yaml
      service: frontend
    depends_on:
      - bweb

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - fweb
