version: '3.8'

services:
  postgresdb:
    extends:
      file: ../pweb-b/docker-compose.yaml
      service: postgresdb
    env_file:
      - ./envs/.env.backend

  redis:
    extends:
      file: ../pweb-b/docker-compose.yaml
      service: redis

  bweb:
    extends:
      file: ../pweb-b/docker-compose.yaml
      service: backend
    env_file:
      - ./envs/.env.backend
    depends_on:
      - postgresdb
      - redis
    links:
      - postgresdb

  fweb:
    extends:
      file: ../pweb-f/docker-compose.yaml
      service: frontend
    env_file:
      - ./envs/.env.frontend
    depends_on:
      - bweb

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - fweb
