version: '3.8'

services:
  postgresdb:
    extends:
      file: ../pweb-b/docker-compose.yaml
      service: postgresdb
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}

  redis:
    extends:
      file: ../pweb-b/docker-compose.yaml
      service: redis

  bweb:
    extends:
      file: ../pweb-b/docker-compose.yaml
      service: backend
    depends_on:
      - postgresdb
      - redis
    environment:
      - DJANGO_ENV:${DJANGO_ENV}
      - SECRET_KEY:${SECRET_KEY}
      - POSTGRES_NAME:${POSTGRES_NAME}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - KAVENEGAR_API:${KAVENEGAR_API}

  fweb:
    extends:
      file: ../pweb-f/docker-compose.yaml
      service: frontend
    depends_on:
      - bweb
    environment:
      - NEXT_PUBLIC_API_URL:${NEXT_PUBLIC_API_URL}

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - "/var/www/ocserv/:/var/www/ocserv/"
    depends_on:
      - fweb
